import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-semiconductor-foundry-yield-settlement-recovery",
  "engine": "recovery",
  "title": "Semiconductor Foundry Yield & Settlement Recovery",
  "shortTitle": "Foundry Settlement Recovery",
  "tagline": "Reconcile wafer starts, good die, yield guarantees, masks, NRE, premium charges, and foundry credits",
  "industry": "Fabless Semiconductor Commercial Operations",
  "uiPort": 4586,
  "apiPort": 5586,
  "accent": "#4f46e5",
  "currency": "USD",
  "primaryOutcome": "Contractually supported foundry yield and invoice value converted into settlements and improved product economics",
  "valueNarrative": "Connect foundry agreements, nodes, masks, wafer lots, wafer sort, good die, yield guarantees, engineering lots, invoices, and credits.",
  "calculation": {
    "actualKey": "creditedAmount",
    "expectedKey": "eligibleSettlement",
    "actualLabel": "Foundry Credits & Settlement",
    "expectedLabel": "Eligible Yield Settlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Wafer, die-yield, agreement, and foundry invoice evidence indicate unrecovered commercial settlement value.",
    "actions": [
      "Validate the governing agreement and effective rules",
      "Reconcile transaction-level source evidence",
      "Prepare and submit the recovery or correction package",
      "Track response and reconcile realized financial outcome"
    ]
  }
},[
feature("foundry-agreement-library","FSR01","Foundry agreement library","Reconcile foundry agreement library using foundry agreements, process nodes, mask sets, wafer starts, lot genealogy, wafer-sort results, good die, yield guarantees, engineering lots, NRE, invoices, and credits.","Produce a governed foundry agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["foundryProduct","Foundry / Product","text","Pacific Foundry / AI-ASIC-42"],["caseReference","Foundry agreement library Reference","text","FSR01-2026-001"],["creditedAmount","Foundry Credits & Settlement","currency",1280000],["eligibleSettlement","Eligible Yield Settlement","currency",1645000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"creditedAmount",subjects:["Advanced-node ASIC","Automotive MCU","RF front-end device","Power semiconductor","Engineering qualification lot"]}),
feature("product-node-and-mask-registry","FSR02","Product node and mask registry","Reconcile product node and mask registry using foundry agreements, process nodes, mask sets, wafer starts, lot genealogy, wafer-sort results, good die, yield guarantees, engineering lots, NRE, invoices, and credits.","Produce a governed product node and mask registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["foundryProduct","Foundry / Product","text","Pacific Foundry / AI-ASIC-42"],["caseReference","Product node and mask registry Reference","text","FSR02-2026-001"],["creditedAmount","Foundry Credits & Settlement","currency",1280000],["eligibleSettlement","Eligible Yield Settlement","currency",1645000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"creditedAmount",subjects:["Advanced-node ASIC","Automotive MCU","RF front-end device","Power semiconductor","Engineering qualification lot"]}),
feature("wafer-start-reconciliation","FSR03","Wafer-start reconciliation","Reconcile wafer-start reconciliation using foundry agreements, process nodes, mask sets, wafer starts, lot genealogy, wafer-sort results, good die, yield guarantees, engineering lots, NRE, invoices, and credits.","Produce a governed wafer-start reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["foundryProduct","Foundry / Product","text","Pacific Foundry / AI-ASIC-42"],["caseReference","Wafer-start reconciliation Reference","text","FSR03-2026-001"],["creditedAmount","Foundry Credits & Settlement","currency",1280000],["eligibleSettlement","Eligible Yield Settlement","currency",1645000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"creditedAmount",subjects:["Advanced-node ASIC","Automotive MCU","RF front-end device","Power semiconductor","Engineering qualification lot"]}),
feature("wafer-acceptance-and-scrap","FSR04","Wafer acceptance and scrap","Reconcile wafer acceptance and scrap using foundry agreements, process nodes, mask sets, wafer starts, lot genealogy, wafer-sort results, good die, yield guarantees, engineering lots, NRE, invoices, and credits.","Produce a governed wafer acceptance and scrap decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["foundryProduct","Foundry / Product","text","Pacific Foundry / AI-ASIC-42"],["caseReference","Wafer acceptance and scrap Reference","text","FSR04-2026-001"],["creditedAmount","Foundry Credits & Settlement","currency",1280000],["eligibleSettlement","Eligible Yield Settlement","currency",1645000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"creditedAmount",subjects:["Advanced-node ASIC","Automotive MCU","RF front-end device","Power semiconductor","Engineering qualification lot"]}),
feature("wafer-sort-ingestion","FSR05","Wafer-sort ingestion","Reconcile wafer-sort ingestion using foundry agreements, process nodes, mask sets, wafer starts, lot genealogy, wafer-sort results, good die, yield guarantees, engineering lots, NRE, invoices, and credits.","Produce a governed wafer-sort ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["foundryProduct","Foundry / Product","text","Pacific Foundry / AI-ASIC-42"],["caseReference","Wafer-sort ingestion Reference","text","FSR05-2026-001"],["creditedAmount","Foundry Credits & Settlement","currency",1280000],["eligibleSettlement","Eligible Yield Settlement","currency",1645000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"creditedAmount",subjects:["Advanced-node ASIC","Automotive MCU","RF front-end device","Power semiconductor","Engineering qualification lot"]}),
feature("good-die-yield-calculation","FSR06","Good-die yield calculation","Reconcile good-die yield calculation using foundry agreements, process nodes, mask sets, wafer starts, lot genealogy, wafer-sort results, good die, yield guarantees, engineering lots, NRE, invoices, and credits.","Produce a governed good-die yield calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["foundryProduct","Foundry / Product","text","Pacific Foundry / AI-ASIC-42"],["caseReference","Good-die yield calculation Reference","text","FSR06-2026-001"],["creditedAmount","Foundry Credits & Settlement","currency",1280000],["eligibleSettlement","Eligible Yield Settlement","currency",1645000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"creditedAmount",subjects:["Advanced-node ASIC","Automotive MCU","RF front-end device","Power semiconductor","Engineering qualification lot"]}),
feature("yield-guarantee-validation","FSR07","Yield guarantee validation","Reconcile yield guarantee validation using foundry agreements, process nodes, mask sets, wafer starts, lot genealogy, wafer-sort results, good die, yield guarantees, engineering lots, NRE, invoices, and credits.","Produce a governed yield guarantee validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["foundryProduct","Foundry / Product","text","Pacific Foundry / AI-ASIC-42"],["caseReference","Yield guarantee validation Reference","text","FSR07-2026-001"],["creditedAmount","Foundry Credits & Settlement","currency",1280000],["eligibleSettlement","Eligible Yield Settlement","currency",1645000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"creditedAmount",subjects:["Advanced-node ASIC","Automotive MCU","RF front-end device","Power semiconductor","Engineering qualification lot"]}),
feature("known-good-die-reconciliation","FSR08","Known-good-die reconciliation","Reconcile known-good-die reconciliation using foundry agreements, process nodes, mask sets, wafer starts, lot genealogy, wafer-sort results, good die, yield guarantees, engineering lots, NRE, invoices, and credits.","Produce a governed known-good-die reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["foundryProduct","Foundry / Product","text","Pacific Foundry / AI-ASIC-42"],["caseReference","Known-good-die reconciliation Reference","text","FSR08-2026-001"],["creditedAmount","Foundry Credits & Settlement","currency",1280000],["eligibleSettlement","Eligible Yield Settlement","currency",1645000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"creditedAmount",subjects:["Advanced-node ASIC","Automotive MCU","RF front-end device","Power semiconductor","Engineering qualification lot"]}),
feature("engineering-lot-separation","FSR09","Engineering lot separation","Reconcile engineering lot separation using foundry agreements, process nodes, mask sets, wafer starts, lot genealogy, wafer-sort results, good die, yield guarantees, engineering lots, NRE, invoices, and credits.","Produce a governed engineering lot separation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["foundryProduct","Foundry / Product","text","Pacific Foundry / AI-ASIC-42"],["caseReference","Engineering lot separation Reference","text","FSR09-2026-001"],["creditedAmount","Foundry Credits & Settlement","currency",1280000],["eligibleSettlement","Eligible Yield Settlement","currency",1645000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"creditedAmount",subjects:["Advanced-node ASIC","Automotive MCU","RF front-end device","Power semiconductor","Engineering qualification lot"]}),
feature("mask-and-nre-charge-audit","FSR10","Mask and NRE charge audit","Reconcile mask and nre charge audit using foundry agreements, process nodes, mask sets, wafer starts, lot genealogy, wafer-sort results, good die, yield guarantees, engineering lots, NRE, invoices, and credits.","Produce a governed mask and nre charge audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["foundryProduct","Foundry / Product","text","Pacific Foundry / AI-ASIC-42"],["caseReference","Mask and NRE charge audit Reference","text","FSR10-2026-001"],["creditedAmount","Foundry Credits & Settlement","currency",1280000],["eligibleSettlement","Eligible Yield Settlement","currency",1645000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"creditedAmount",subjects:["Advanced-node ASIC","Automotive MCU","RF front-end device","Power semiconductor","Engineering qualification lot"]}),
feature("expedite-charge-validation","FSR11","Expedite charge validation","Reconcile expedite charge validation using foundry agreements, process nodes, mask sets, wafer starts, lot genealogy, wafer-sort results, good die, yield guarantees, engineering lots, NRE, invoices, and credits.","Produce a governed expedite charge validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["foundryProduct","Foundry / Product","text","Pacific Foundry / AI-ASIC-42"],["caseReference","Expedite charge validation Reference","text","FSR11-2026-001"],["creditedAmount","Foundry Credits & Settlement","currency",1280000],["eligibleSettlement","Eligible Yield Settlement","currency",1645000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"creditedAmount",subjects:["Advanced-node ASIC","Automotive MCU","RF front-end device","Power semiconductor","Engineering qualification lot"]}),
feature("foundry-invoice-recalculation","FSR12","Foundry invoice recalculation","Reconcile foundry invoice recalculation using foundry agreements, process nodes, mask sets, wafer starts, lot genealogy, wafer-sort results, good die, yield guarantees, engineering lots, NRE, invoices, and credits.","Produce a governed foundry invoice recalculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["foundryProduct","Foundry / Product","text","Pacific Foundry / AI-ASIC-42"],["caseReference","Foundry invoice recalculation Reference","text","FSR12-2026-001"],["creditedAmount","Foundry Credits & Settlement","currency",1280000],["eligibleSettlement","Eligible Yield Settlement","currency",1645000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"creditedAmount",subjects:["Advanced-node ASIC","Automotive MCU","RF front-end device","Power semiconductor","Engineering qualification lot"]}),
feature("yield-loss-claim-generation","FSR13","Yield-loss claim generation","Reconcile yield-loss claim generation using foundry agreements, process nodes, mask sets, wafer starts, lot genealogy, wafer-sort results, good die, yield guarantees, engineering lots, NRE, invoices, and credits.","Produce a governed yield-loss claim generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["foundryProduct","Foundry / Product","text","Pacific Foundry / AI-ASIC-42"],["caseReference","Yield-loss claim generation Reference","text","FSR13-2026-001"],["creditedAmount","Foundry Credits & Settlement","currency",1280000],["eligibleSettlement","Eligible Yield Settlement","currency",1645000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"creditedAmount",subjects:["Advanced-node ASIC","Automotive MCU","RF front-end device","Power semiconductor","Engineering qualification lot"]}),
feature("foundry-response-workflow","FSR14","Foundry response workflow","Reconcile foundry response workflow using foundry agreements, process nodes, mask sets, wafer starts, lot genealogy, wafer-sort results, good die, yield guarantees, engineering lots, NRE, invoices, and credits.","Produce a governed foundry response workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["foundryProduct","Foundry / Product","text","Pacific Foundry / AI-ASIC-42"],["caseReference","Foundry response workflow Reference","text","FSR14-2026-001"],["creditedAmount","Foundry Credits & Settlement","currency",1280000],["eligibleSettlement","Eligible Yield Settlement","currency",1645000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"creditedAmount",subjects:["Advanced-node ASIC","Automotive MCU","RF front-end device","Power semiconductor","Engineering qualification lot"]}),
feature("credit-reconciliation","FSR15","Credit reconciliation","Reconcile credit reconciliation using foundry agreements, process nodes, mask sets, wafer starts, lot genealogy, wafer-sort results, good die, yield guarantees, engineering lots, NRE, invoices, and credits.","Produce a governed credit reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["foundryProduct","Foundry / Product","text","Pacific Foundry / AI-ASIC-42"],["caseReference","Credit reconciliation Reference","text","FSR15-2026-001"],["creditedAmount","Foundry Credits & Settlement","currency",1280000],["eligibleSettlement","Eligible Yield Settlement","currency",1645000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"creditedAmount",subjects:["Advanced-node ASIC","Automotive MCU","RF front-end device","Power semiconductor","Engineering qualification lot"]}),
feature("product-node-and-supplier-analytics","FSR16","Product node and supplier analytics","Reconcile product node and supplier analytics using foundry agreements, process nodes, mask sets, wafer starts, lot genealogy, wafer-sort results, good die, yield guarantees, engineering lots, NRE, invoices, and credits.","Produce a governed product node and supplier analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["foundryProduct","Foundry / Product","text","Pacific Foundry / AI-ASIC-42"],["caseReference","Product node and supplier analytics Reference","text","FSR16-2026-001"],["creditedAmount","Foundry Credits & Settlement","currency",1280000],["eligibleSettlement","Eligible Yield Settlement","currency",1645000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"creditedAmount",subjects:["Advanced-node ASIC","Automotive MCU","RF front-end device","Power semiconductor","Engineering qualification lot"]})
]);
